settings:
  title: 'Solomonic Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: changirecommends-com-sg # unique identifier
    name: www.changirecommends.com.sg
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.changirecommends.com.sg' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: horme-com-sg
    name: www.horme.com.sg
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.horme.com.sg/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
